name: static analysis
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: clippy, rustfmt
    - uses: Swatinem/rust-cache@v1.3.0
    - name: make check
      run: make
    - name: check git status
      run: git diff --exit-code
